server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jwt?serverTimezone=UTC
      username: root
      password: 123456
#logging:
#  level:
#    root: info
#    com.wzj.dao: debug
#    com.wzj.service: debug
#    com.wzj.controller: debug
mybatis:
  mapper-locations: classpath:mybatis/*.xml
